### ISSUE TITLE
MicroDAQ causes segfault when disk is full

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/ApplicationCore#19]
I guess closing the file in the exception handling does not work if the disk is full.
https://github.com/ChimeraTK/ApplicationCore/blob/a8bafe001f4c0d8d2d6a4dd907fa59602a4ea05a/Modules/src/MicroDAQ.cc#L360

See backtrace:
```
#0  0x00007f0134f0c428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f0134f0e02a in __GI_abort () at abort.c:89
#2  0x00007f013554684d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f01355446b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f0135544701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f0135544969 in __cxa_rethrow () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f013750a6d2 in ChimeraTK::detail::H5storage::writeData() () from /usr/lib/libChimeraTK-ApplicationCore.so.01.02xenial2
#7  0x00007f013750ad34 in ChimeraTK::detail::H5storage::processTrigger() () from /usr/lib/libChimeraTK-ApplicationCore.so.01.02xenial2
#8  0x00007f013750d00b in ChimeraTK::MicroDAQ::mainLoop() () from /usr/lib/libChimeraTK-ApplicationCore.so.01.02xenial2
#9  0x00007f01374e2b20 in ChimeraTK::ApplicationModule::mainLoopWrapper() () from /usr/lib/libChimeraTK-ApplicationCore.so.01.02xenial2
#10 0x00007f0136c2f5d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
#11 0x00007f01360086ba in start_thread (arg=0x7f0021ffb700) at pthread_create.c:333
#12 0x00007f0134fde41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by mhier** [comment]
if this is still a problem, please create a ticket in the separate MicroDAQ project.
